package:
    name: peek
    version: "0.2"

source:
    git_rev: v0.2
    git_url: https://github.umn.edu/mpc/peek.git

requirements:
    build:
        - python
        - setuptools

    run:
        - python

about:
    home: https://github.umn.edu/mpc/peek
    license: MIT
    license_file: LICENSE
